version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: brandkit-backend
    env_file:
      - .env  # Provide OPENAI_API_KEY here
    volumes:
      - ./backend:/app
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: brandkit-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid syncing node_modules from host
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    ports:
      - "5173:5173"
    command: npm run dev -- --host --port 5173
    depends_on:
      - backend
    restart: unless-stopped 